/* Generated by cbindgen — do not edit manually */

#ifndef HEXATUNE_DSP_FFI_H
#define HEXATUNE_DSP_FFI_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Default sample rate for mobile audio.
 */
#define DEFAULT_SAMPLE_RATE 48000.0

/**
 * Default rain gain.
 */
#define DEFAULT_RAIN_GAIN 0.8

/**
 * Default tone gain.
 */
#define DEFAULT_TONE_GAIN 0.2

/**
 * The main DSP audio engine.
 *
 * # Thread Safety
 *
 * The engine uses a split ownership model:
 * - **Audio thread** calls [`render`] exclusively (no concurrent calls).
 * - **Control thread** calls atomic setters and [`queue_config_update`].
 *
 * The control thread must not call [`render`]. The audio thread must not
 * call [`queue_config_update`] or atomic setters (it reads them).
 */
typedef struct Engine Engine;

/**
 * Opaque engine handle. Do not access fields directly.
 */
typedef struct Engine HtdEngine;

/**
 * A single cycle item passed from Flutter.
 */
typedef struct HtdCycleItem {
  float frequency_delta;
  float duration_seconds;
} HtdCycleItem;

/**
 * Engine configuration passed from Flutter.
 */
typedef struct HtdEngineConfig {
  float carrier_frequency;
  bool binaural_enabled;
  /**
   * Null-terminated UTF-8 path, or null if no rain sound.
   */
  const char *rain_sound_path;
  /**
   * Pointer to an array of cycle items.
   */
  const struct HtdCycleItem *cycle_items;
  /**
   * Number of cycle items.
   */
  uint32_t cycle_count;
  float sample_rate;
  float rain_gain;
  float tone_gain;
} HtdEngineConfig;

/**
 * A stereo audio frame (used for documentation / cbindgen export).
 */
typedef struct HtdStereoFrame {
  float left;
  float right;
} HtdStereoFrame;

/**
 * Initialize the DSP engine with the given configuration.
 *
 * Returns an opaque engine pointer on success, or null on failure.
 * The error code is written to `out_error` if non-null.
 *
 * # Safety
 *
 * - `config` must point to a valid `HtdEngineConfig`.
 * - The returned pointer must be freed with [`htd_engine_destroy`].
 */
HtdEngine *htd_engine_init(const struct HtdEngineConfig *config, int32_t *out_error);

/**
 * Destroy the engine and free all associated memory.
 *
 * # Safety
 *
 * - `engine` must be a pointer returned by [`htd_engine_init`].
 * - Must not be called while [`htd_engine_render`] is in progress.
 * - After this call, the pointer is invalid.
 */
void htd_engine_destroy(HtdEngine *engine);

/**
 * Start audio generation. After this call, [`htd_engine_render`] will
 * produce audio samples instead of silence.
 *
 * # Safety
 *
 * `engine` must be a valid engine pointer.
 */
int32_t htd_engine_start(HtdEngine *engine);

/**
 * Stop audio generation. [`htd_engine_render`] will output silence.
 *
 * # Safety
 *
 * `engine` must be a valid engine pointer.
 */
int32_t htd_engine_stop(HtdEngine *engine);

/**
 * Render `num_frames` of interleaved stereo f32 audio into `output`.
 *
 * The output buffer must hold at least `num_frames * 2` floats
 * (left, right, left, right, ...).
 *
 * # Real-time safety
 *
 * This function is safe to call from an audio callback. It does not
 * allocate, does not perform I/O, and does not block.
 *
 * # Safety
 *
 * - `engine` must be a valid engine pointer.
 * - `output` must point to a buffer of at least `num_frames * 2` f32 values.
 * - Must not be called concurrently with itself or [`htd_engine_destroy`].
 */
int32_t htd_engine_render(HtdEngine *engine, float *output, uint32_t num_frames);

/**
 * Set the rain/ambient gain level. Can be called from any thread.
 *
 * # Safety
 *
 * `engine` must be a valid engine pointer.
 */
int32_t htd_engine_set_rain_gain(HtdEngine *engine, float gain);

/**
 * Set the tone gain level. Can be called from any thread.
 *
 * # Safety
 *
 * `engine` must be a valid engine pointer.
 */
int32_t htd_engine_set_tone_gain(HtdEngine *engine, float gain);

/**
 * Update the engine configuration at runtime. Changes are applied on the
 * next render call. This function may be called from any thread.
 *
 * Fields in the config are applied as follows:
 * - `carrier_frequency`: updated if > 0
 * - `binaural_enabled`: always applied
 * - `cycle_items` / `cycle_count`: updated if `cycle_items` is non-null
 *   and `cycle_count` > 0
 *
 * `rain_sound_path`, `sample_rate`, and gain fields are ignored.
 * Use dedicated setters for gains.
 *
 * # Safety
 *
 * `engine` and `config` must be valid pointers.
 */
int32_t htd_engine_update_config(HtdEngine *engine, const struct HtdEngineConfig *config);

/**
 * Load a rain/ambient sound from a WAV file.
 *
 * This function allocates memory and performs I/O. It must NOT be called
 * from an audio callback.
 *
 * # Safety
 *
 * - `engine` must be a valid engine pointer.
 * - `path` must be a valid null-terminated UTF-8 string.
 * - Must not be called concurrently with [`htd_engine_render`].
 */
int32_t htd_engine_load_rain(HtdEngine *engine, const char *path);

/**
 * Query whether the engine is currently running.
 *
 * Returns `1` if running, `0` if stopped, or a negative error code.
 *
 * # Safety
 *
 * `engine` must be a valid engine pointer.
 */
int32_t htd_engine_is_running(const HtdEngine *engine);

/**
 * Return the engine's sample rate.
 *
 * # Safety
 *
 * `engine` must be a valid engine pointer.
 */
float htd_engine_sample_rate(const HtdEngine *engine);

#endif  /* HEXATUNE_DSP_FFI_H */
