/* Generated by cbindgen — do not edit manually */

#ifndef HEXATUNE_DSP_FFI_H
#define HEXATUNE_DSP_FFI_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Default sample rate for mobile audio.
 */
#define DEFAULT_SAMPLE_RATE 48000.0

/**
 * Maximum number of texture layers.
 */
#define MAX_TEXTURE_LAYERS 3

/**
 * Maximum number of event slots.
 */
#define MAX_EVENT_SLOTS 5

/**
 * Default gain values for each layer.
 */
#define DEFAULT_BASE_GAIN 0.6

#define DEFAULT_TEXTURE_GAIN 0.3

#define DEFAULT_EVENT_GAIN 0.4

#define DEFAULT_BINAURAL_GAIN 0.15

#define DEFAULT_MASTER_GAIN 1.0

/**
 * Default crossfade length in sample frames (~42 ms at 48 kHz).
 */
#define DEFAULT_CROSSFADE_FRAMES 2048

/**
 * Error codes returned by FFI functions.
 */
enum HtdError {
  Ok = 0,
  NullPointer = -1,
  InvalidConfig = -2,
  InitFailed = -3,
  InvalidUtf8 = -4,
  BufferTooSmall = -5,
  LoadFailed = -6,
  LayerLimitExceeded = -7,
  BaseRequired = -8,
};
typedef int32_t HtdError;

/**
 * The main DSP audio engine.
 *
 * # Thread Safety
 *
 * The engine uses a split ownership model:
 * - **Audio thread** calls [`render`] exclusively (no concurrent calls).
 * - **Control thread** calls atomic setters and [`queue_config_update`].
 *
 * The control thread must not call [`render`]. The audio thread must not
 * call [`queue_config_update`] or atomic setters (it reads them).
 */
typedef struct Engine Engine;

/**
 * Opaque engine handle. Do not access fields directly.
 */
typedef struct Engine HtdEngine;

/**
 * A single cycle item passed from Flutter.
 */
typedef struct HtdCycleItem {
  float frequency_delta;
  float duration_seconds;
  /**
   * If true, this item plays only in the first cycle iteration.
   */
  bool oneshot;
} HtdCycleItem;

/**
 * Engine configuration passed from Flutter.
 */
typedef struct HtdEngineConfig {
  float carrier_frequency;
  bool binaural_enabled;
  /**
   * Pointer to an array of cycle items.
   */
  const struct HtdCycleItem *cycle_items;
  /**
   * Number of cycle items.
   */
  uint32_t cycle_count;
  float sample_rate;
  float base_gain;
  float texture_gain;
  float event_gain;
  float binaural_gain;
  float master_gain;
} HtdEngineConfig;

/**
 * Audio layer configuration (raw PCM data).
 */
typedef struct HtdLayerConfig {
  /**
   * Pointer to interleaved f32 PCM samples.
   */
  const float *samples;
  /**
   * Number of sample frames (not individual samples).
   */
  uint32_t num_frames;
  /**
   * Number of channels: 1 (mono) or 2 (stereo interleaved).
   */
  uint32_t channels;
} HtdLayerConfig;

/**
 * Random event configuration.
 */
typedef struct HtdEventConfig {
  /**
   * Pointer to interleaved f32 PCM samples.
   */
  const float *samples;
  /**
   * Number of sample frames.
   */
  uint32_t num_frames;
  /**
   * Number of channels: 1 (mono) or 2 (stereo interleaved).
   */
  uint32_t channels;
  /**
   * Minimum interval between triggers in milliseconds.
   */
  uint32_t min_interval_ms;
  /**
   * Maximum interval between triggers in milliseconds.
   */
  uint32_t max_interval_ms;
  /**
   * Minimum playback volume (0.0–1.0).
   */
  float volume_min;
  /**
   * Maximum playback volume (0.0–1.0).
   */
  float volume_max;
  /**
   * Minimum stereo pan (-1.0 = left, 1.0 = right).
   */
  float pan_min;
  /**
   * Maximum stereo pan (-1.0 = left, 1.0 = right).
   */
  float pan_max;
} HtdEventConfig;

/**
 * A stereo audio frame (used for documentation / cbindgen export).
 */
typedef struct HtdStereoFrame {
  float left;
  float right;
} HtdStereoFrame;

/**
 * Initialize the DSP engine with the given configuration.
 *
 * Returns an opaque engine pointer on success, or null on failure.
 * The error code is written to `out_error` if non-null.
 *
 * # Safety
 *
 * - `config` must point to a valid `HtdEngineConfig`.
 * - The returned pointer must be freed with [`htd_engine_destroy`].
 */
HtdEngine *htd_engine_init(const struct HtdEngineConfig *config, int32_t *out_error);

/**
 * Destroy the engine and free all associated memory.
 *
 * # Safety
 *
 * - `engine` must be a pointer returned by [`htd_engine_init`].
 * - Must not be called while [`htd_engine_render`] is in progress.
 * - After this call, the pointer is invalid.
 */
void htd_engine_destroy(HtdEngine *engine);

/**
 * Start audio generation.
 *
 * # Safety
 *
 * `engine` must be a valid engine pointer.
 */
int32_t htd_engine_start(HtdEngine *engine);

/**
 * Stop audio generation. [`htd_engine_render`] will output silence.
 *
 * # Safety
 *
 * `engine` must be a valid engine pointer.
 */
int32_t htd_engine_stop(HtdEngine *engine);

/**
 * Request a graceful stop: the engine finishes the current cycle iteration
 * (all remaining items in this pass) and then automatically stops.
 *
 * Ambience, texture, and event layers will also go silent once the cycle
 * completes.
 *
 * # Safety
 *
 * `engine` must be a valid engine pointer.
 */
int32_t htd_engine_stop_graceful(HtdEngine *engine);

/**
 * Render `num_frames` of interleaved stereo f32 audio into `output`.
 *
 * # Real-time safety
 *
 * Safe to call from an audio callback.
 *
 * # Safety
 *
 * - `engine` must be a valid engine pointer.
 * - `output` must point to a buffer of at least `num_frames * 2` f32 values.
 * - Must not be called concurrently with itself or [`htd_engine_destroy`].
 */
int32_t htd_engine_render(HtdEngine *engine, float *output, uint32_t num_frames);

/**
 * Set the base ambient layer from raw PCM data.
 *
 * # Safety
 *
 * - `engine` must be a valid engine pointer.
 * - `config` must point to a valid `HtdLayerConfig` with valid `samples`.
 * - Must not be called concurrently with [`htd_engine_render`].
 */
int32_t htd_engine_set_base(HtdEngine *engine, const struct HtdLayerConfig *config);

/**
 * Remove the base layer and all dependent layers (textures, events).
 *
 * # Safety
 *
 * `engine` must be a valid engine pointer.
 * Must not be called concurrently with [`htd_engine_render`].
 */
int32_t htd_engine_clear_base(HtdEngine *engine);

/**
 * Set a texture layer at the given index (0–2).
 *
 * # Safety
 *
 * - `engine` must be a valid engine pointer.
 * - `config` must point to valid `HtdLayerConfig`.
 * - Must not be called concurrently with [`htd_engine_render`].
 */
int32_t htd_engine_set_texture(HtdEngine *engine,
                               uint32_t index,
                               const struct HtdLayerConfig *config);

/**
 * Remove a texture layer at the given index.
 *
 * # Safety
 *
 * `engine` must be a valid engine pointer.
 * Must not be called concurrently with [`htd_engine_render`].
 */
int32_t htd_engine_clear_texture(HtdEngine *engine, uint32_t index);

/**
 * Register a random event at the given index (0–4).
 *
 * # Safety
 *
 * - `engine` must be a valid engine pointer.
 * - `config` must point to valid `HtdEventConfig`.
 * - Must not be called concurrently with [`htd_engine_render`].
 */
int32_t htd_engine_set_event(HtdEngine *engine,
                             uint32_t index,
                             const struct HtdEventConfig *config);

/**
 * Remove a random event at the given index.
 *
 * # Safety
 *
 * `engine` must be a valid engine pointer.
 * Must not be called concurrently with [`htd_engine_render`].
 */
int32_t htd_engine_clear_event(HtdEngine *engine, uint32_t index);

/**
 * Remove all layers (base, textures, events). Binaural is unaffected.
 *
 * # Safety
 *
 * `engine` must be a valid engine pointer.
 * Must not be called concurrently with [`htd_engine_render`].
 */
int32_t htd_engine_clear_all_layers(HtdEngine *engine);

/**
 * Set the base layer gain. Thread-safe (atomic).
 *
 * # Safety
 *
 * `engine` must be a valid engine pointer.
 */
int32_t htd_engine_set_base_gain(HtdEngine *engine, float gain);

/**
 * Set the texture layer gain. Thread-safe (atomic).
 *
 * # Safety
 *
 * `engine` must be a valid engine pointer.
 */
int32_t htd_engine_set_texture_gain(HtdEngine *engine, float gain);

/**
 * Set the event layer gain. Thread-safe (atomic).
 *
 * # Safety
 *
 * `engine` must be a valid engine pointer.
 */
int32_t htd_engine_set_event_gain(HtdEngine *engine, float gain);

/**
 * Set the binaural/tone layer gain. Thread-safe (atomic).
 *
 * # Safety
 *
 * `engine` must be a valid engine pointer.
 */
int32_t htd_engine_set_binaural_gain(HtdEngine *engine, float gain);

/**
 * Set the master output gain. Thread-safe (atomic).
 *
 * # Safety
 *
 * `engine` must be a valid engine pointer.
 */
int32_t htd_engine_set_master_gain(HtdEngine *engine, float gain);

/**
 * Update the engine binaural configuration at runtime.
 *
 * Fields applied:
 * - `carrier_frequency`: updated if > 0
 * - `binaural_enabled`: always applied
 * - `cycle_items` / `cycle_count`: updated if non-null and count > 0
 *
 * Gain fields and `sample_rate` are ignored — use dedicated setters.
 *
 * # Safety
 *
 * `engine` and `config` must be valid pointers.
 */
int32_t htd_engine_update_config(HtdEngine *engine, const struct HtdEngineConfig *config);

/**
 * Load a base layer from a WAV file (convenience function).
 *
 * This allocates memory and performs I/O.
 *
 * # Safety
 *
 * - `engine` must be a valid engine pointer.
 * - `path` must be a valid null-terminated UTF-8 string.
 * - Must not be called concurrently with [`htd_engine_render`].
 */
int32_t htd_engine_load_base_wav(HtdEngine *engine, const char *path);

/**
 * Query whether the engine is currently running.
 *
 * Returns `1` if running, `0` if stopped, or a negative error code.
 *
 * # Safety
 *
 * `engine` must be a valid engine pointer.
 */
int32_t htd_engine_is_running(const HtdEngine *engine);

/**
 * Return the engine's sample rate.
 *
 * # Safety
 *
 * `engine` must be a valid engine pointer.
 */
float htd_engine_sample_rate(const HtdEngine *engine);

#endif  /* HEXATUNE_DSP_FFI_H */
